#! /bin/sh

script_name="${0##*/}"

show_help() {
	cat <<HELP
Usage: ${script_name} [options] command [args...]

Forces config and rc files for tools into \$XDG_CONFIG_HOME instead of \$HOME

Options:
--help   	Display this message
--version	Display version
HELP
	exit
}

show_version() {
	cat <<VERSION
${script_name}, version 1.0 2015-03-27
VERSION
	exit 1
}

unset man
unset command
unset config_dir
unset arg

if [ $# = 0 ]; then
	show_help
fi

#loop through args, remove current arg from list as we go
for arg in $@; do
	case $arg in
		--version )
			show_version
			exit 1;;
		--help|-help|help)
			show_help
			exit 1;;
	esac
done

#if no args left, then show_help and exit
if [ $# = 0 ]; then
	show_help
fi

command="$1"

if [ -n ${XDG_CONFIG_HOME} ]; then
	XDG_CONFIG_HOME=${HOME}/.config
fi

config_dir="${XDG_CONFIG_HOME}/${command}"

if [ ! -d ${config_dir} ]; then
	mkdir -p ${config_dir}
	if [ 0 -ne $? ]; then
		echo "${script_name}: FATAL: could not create ${config_dir}"
		exit
	fi
fi
HOME=${config_dir} exec "$@"
